# Generated by Django 2.2.7 on 2020-06-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, default='PENDING_VERIFICATION', max_length=64)),
                ('topic', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription_from', models.DateTimeField(blank=True)),
                ('subscription_to', models.DateTimeField(blank=True)),
                ('subscription_status', models.CharField(blank=True, default='IDLE', max_length=64)),
                ('email_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tweet_subscribers',
            },
        ),
    ]
