# Generated by Django 2.2.7 on 2020-06-30 16:40

from django.db import migrations, models
import django.db.models.deletion


def populate_subscription_plan(apps, schema_editor):
    SubscriptionPlanModel = apps.get_model("subscriber", "SubscriptionPlanModel")
    SubscriptionPlanModel.objects.get_or_create(
        id=1,
        plan_name='BASIC',
        topic_quota='10'
    )
    SubscriptionPlanModel.objects.get_or_create(
        id=2,
        plan_name='STANDARD',
        topic_quota='25'
    )
    SubscriptionPlanModel.objects.get_or_create(
        id=3,
        plan_name='PREMIUM',
        topic_quota='50'
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlanModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=100)),
                ('topic_quota', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tweet_subscription_plans',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=200, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, default='PENDING_VERIFICATION', max_length=64)),
                ('plan_subscribed', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subscriber.SubscriptionPlanModel')),
            ],
            options={
                'db_table': 'tweet_subscribers',
            },
        ),
        migrations.CreateModel(
            name='SubscribeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription_from', models.DateTimeField(blank=True)),
                ('subscription_to', models.DateTimeField(blank=True)),
                ('subscription_status', models.CharField(blank=True, default='IDLE', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subscriber.UserModel')),
            ],
            options={
                'db_table': 'tweet_subscriptions',
            },
        ),
        migrations.RunPython(populate_subscription_plan),
    ]
